# This action is hidden from the GitHub Actions UI
name: 'Build Instance Repo Pipeline Docker Image'
description: 'Build and push Instance Repo Pipeline docker image to container registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  repository-owner:
    description: 'Repository owner for Docker images'
    required: false
    default: 'netcracker'
  image-name:
    description: 'Docker image name'
    required: false
    default: 'qubership-instance-repo-pipeline'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './github_workflows/instance-repo-pipeline/Dockerfile'
  gh-access-token:
    description: 'GitHub access token for build args'
    required: false
  github-token:
    description: 'GitHub token for registry login'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Generate custom tags with timestamp
      id: tags
      shell: bash
      run: |
        # Transform branch name to docker tag format
        BRANCH_NAME="${{ github.ref_name }}"
        DOCKER_TAG=$(echo "$BRANCH_NAME" | sed 's|/|_|g')
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        CUSTOM_TAG="${DOCKER_TAG}_${TIMESTAMP}"
        BRANCH_LATEST_TAG="${DOCKER_TAG}"
        
        # Set output for next steps
        echo "custom_tag=$CUSTOM_TAG" >> $GITHUB_OUTPUT
        echo "branch_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "branch_latest_tag=$BRANCH_LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-{{sha}},suffix={{timestamp}}
          type=raw,value={{branch}}_{{timestamp}}
    
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.image-name }}:${{ steps.tags.outputs.custom_tag }}
          ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.image-name }}:${{ steps.tags.outputs.branch_latest_tag }}
          ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GH_ACCESS_TOKEN=${{ inputs.gh-access-token }} 