---
tenant: "{{ templates_dir }}/env_templates/dev/tenant.yml.j2"
cloud: "{{ templates_dir }}/env_templates/dev/cloud.yml.j2"
namespaces:
  - template_path: "{{ templates_dir }}/env_templates/dev/Namespaces/core.yml.j2"
  - template_path: "{{ templates_dir }}/env_templates/dev/Namespaces/bss.yml.j2"
