name: Build and Archive Templates

on:
  workflow_dispatch:

jobs:
  prefix_build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ct_skip]')" # Аналог rules
    container:
      image: ghcr.io/netcracker/qubership-build-envgene:main
      options: --entrypoint /bin/bash
    env:
      module_ansible_dir: /module/ansible
      module_inventory: ${{ github.workspace }}/configuration/inventory.yaml
      module_ansible_cfg: /module/ansible/ansible.cfg
      module_config_default: /module/templates/defaults.yaml
      GITHUB_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GITHUB_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      ENV_NAME: my_environment
      CLUSTER_NAME: my_cluster
      ENVIRONMENT_NAME: my_environment_name
      DEPLOYMENT_TICKET_ID: ticket_12345
      COMMIT_ENV: false
      COMMIT_MESSAGE: "Automated commit [ci_skip]"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Parameters Containers
        run: python3 /build_env/scripts/build_env/prepare_env_templates.py

      - name: Prepare Git Commit
        run: /module/scripts/prepare.sh "git_commit.yaml"
